export const agendaTranslations = {
    en: {
        day1: "Warm Up",
        day2: "Day 1",
        day3: "Day 2",
        day4: "Day 3",
        download: "Get the PDF",
        "day1_schedule": "Warm Up - September 10th - Tuesday",
        "time_1200": "12:00 PM",
        "time_1700": "5:00 PM",
        "time_1800": "6:00 PM",
        "early_reg": "Early Registration",  
        "departure1": "1st Departure to Itaipu Power Plant",
        "panoramic": "Panoramic View",
        "panoramic_text": "Welcome Reception at Illuminated Itaipu Power Plant and Cultural Presentation",
        "departure2": "2nd Departure to Itaipu Power Plant",
        "reception": "Welcome Reception at Illuminated Itaipu Power Plant",
        "time_2000": "8:00 PM",
        "time_2100": "9:00 PM",
        "return1": "1st Return to Recanto Cataratas Thermas Resort & Convention",
        "return2": "2nd Return to Recanto Cataratas Thermas Resort & Convention",
        "day2_schedule": "Day 1 - September 11th - Wednesday",
        "day3_schedule": "Day 2 - September 12th - Thursday",
        "day4_schedule": "Day 3 - September 13th - Friday",
        "registration": "Registration",
        "opening_Session": "Opening Session",
        "opening": "Opening Session by the Hosts",
        "coffee": "Coffee Break and Opening of Exhibition",
        "heads_of_space_agencies_session": "Heads of Space Agencies Session",
        "speech": "Speech by Brazilian Authorities",
        "introduction": "Introduction to the current edition's theme – Head, AEB",
        "experience_sharing": "Experience sharing by the Previous Edition's SELM Host – Head, ISRO",
        "head_SANSA": "Message from the upcoming SELM Host - Head, SANSA",
        "message_host": "Statements on the theme (3-minute statements each, Heads of Agencies + invited countries) Message from the upcoming SELM Host - Head, SANSA",
        "photo": "Group Photo",
        "lunch": "Lunch Break",
        "lunch_break": "Lunch Break and Visit to Exhibition",
        "exhibition_opening": "Exhibition Opening",
        "3_minute": "3-minute statements each, Heads of Agencies",
        "coffee_Snacks": "Coffee and Snacks served during Session",
        "declaration_introduction": "Declaration Introduction",
        "presentation": "Presentation of the Declaration - Head, AEB",
        "impressions": "Impressions of the Declaration - List of Speakers, G20 Members Only",
        "invited": "Invited Space Agencies and Guests Statements on the Theme",
        "panel_1": "Panel 1",
        "panel_1_description": "This panel will explore the complex connection between the urgent issue of climate change and the objective of sustainable development. The discussion will center on the challenges and opportunities when striving to effectively integrate climate change and sustainable development.",
        "climate_change_and_sustainable_development": "Climate Change and Sustainable Development",
        "panelists": "Panelists: Invited Speakers and G20 HoA, 10 minutes each",
        "Moderator": "Moderator: Ms. Leila Fonseca (AEB Coordinator of Strategic Studies and New Business)",
        "challenges": "Challenges and opportunities of integrating climate change and sustainable development",
        "coffee2": "Coffee Break and Visit to Exhibition",
        "keynote_speech": "Keynote Speech: Thelma Krug (WMO)",
        "space_climate": "Space and Climate Change: Challenges and Opportunities",
        "adjourn": "Adjourn",
        "gala": "Gala Dinner",
        "cultural": "Reception (illuminated Itaipu Power Plant) and Cultural Presentation",
        "panel_2": "Panel 2",
        "panel_2_description": "This panel will explore the intersection of space economy and climate change mitigation, emphasizing the need for coordinated strategies involving governments, international organizations, private sector entities, and local communities.",
        "Space_Economy_and_Climate_Change_Mitigation": "Space Economy and Climate Change Mitigation: strategies for coordinated action",
        "panelists_hoa": "Panelists: Invited Speakers and HoA, 10 minutes each",
        "Moderator_Chamon": "Moderator: Mr. Marco Antonio Chamon (AEB President)",
        "Moderator_AEB": "Moderator: AEB",
        "space_economy": "Space Economy and Climate Change Mitigation: strategies for action coordination",
        "hoa": "Space initiatives on mitigating climate change",
        "remarks": "Final Remarks",
        "ceremony": "Signing Ceremony of the Declaration",
        "dinner": "Festive Dinner",
        "panel_3": "Panel 3",
        "Moderator_Panel_3": "Moderator: Mr. Rodrigo Leonardi (AEB Portfolio Management Director)",
        "panel_3_description": "The panel will discuss how space-based technologies can help address the urgent issue of climate change. By assembling experts and leaders of space agencies, the panel will explore the distinctive perspectives and capabilities that space provides to confront this intricate global challenge.",
        "space_initiatives": "Space Initiatives on Mitigating Climate Change",
        "declaration_discussion_and_signature": "Declaration Discussion and Signature",
        "Moderator_Panel_4": "Moderator: Mr. Paolo Gessini (AEB Director of Strategic Intelligence & New Business)",
        
        "0800_0900": "8:00 AM - 9:00 AM",
        "0900_0945": "9:00 AM - 9:45 AM",
        "0900_1030": "9:00 AM - 10:30 AM",
        "0945_1015": "09:45 AM - 10:15 AM",
        "1145_1315": "11:45 AM - 13:15 PM",
        "1030_1100": "10:30 AM - 11:00 AM",
        "1100_1230": "11:00 AM - 12:30 PM",
        "1230_1300": "12:30 PM - 1:00 PM",
        "1015_1045": "10:15 PM - 10:45 PM",
        "1200_1400": "12:30 PM - 2:00 PM",
        "1300_1400": "1:00 PM - 2:00 PM",
        "1300_1430": "1:00 PM - 2:30 PM",
        "1315_1430": "1:15 PM - 2:30 PM",
        "1400_1500": "2:00 PM - 3:00 PM",
        "1430_1500": "2:30 PM - 3:00 PM",
        "1430_1530": "2:30 PM - 3:30 PM",
        "1430": "2:30 PM",
        "1500_1530": "3:00 PM - 3:30 PM",
        "1530_1600": "3:30 PM - 4:00 PM",
        "1500_1700": "3:00 PM - 5:00 PM",
        "1530_1700": "3:30 PM - 5:00 PM",
        "1600_1800": "4:00 PM - 6:00 PM",
        "1600_1700": "4:00 PM - 5:00 PM",
        "1700_1800": "5:00 PM - 6:00 PM",
        "1700_1730": "5:00 PM - 5:30 PM",
        "1700": "5:00 PM",
        "1730_1830": "5:30 PM - 6:30 PM",
        "1800_1900": "6:00 PM - 7:00 PM",
        "1830_1930": "6:30 PM - 7:30 PM",
        "1900": "7:00 PM",
        "1930_2200": "7:30 PM - 10:00 PM",
        "1900_2200": "7:00 PM - 10:00 PM",
        "2200": "10:00 PM",
        "2300": "11:00 PM",
        "1045_1145": "10:45 PM – 11:45 PM",


        "g20_statements": "G20 Statements on the theme",
        "3_minute_statements": "(3-minute statements each, Heads of Agencies)",
        "coffee_snacks": "(Coffee and Snacks served during Session)",

        "90seconds": "90 seconds statements each",
        "declaration": "Declaration Adoption",
        "keynote_speech_unoosa": "Keynote Speech: Aarti Holla-Maini (UNOOSA)",
        "special_session_isro": "Special Session: ISRO's G20 Satellite Mission",
        "speaker_isro": "Speaker: ISRO",
        "session_chair_isro": "Session Chair: Márcia Alvarenga, Head of the International Cooperation Office (Brazilian Space Agency (AEB))",
        "departure_to_festive_reception": "Departure to Festive Reception",
        "festive_reception": "Festive Reception",
        "first_return": "1st Return to Recanto Cataratas Thermas Resort & Convention",
        "second_return": "2nd Return to Recanto Cataratas Thermas Resort & Convention",
        "space_driver": "Space as a Driver for Climate Change Action",
        "panel_4": "Panel 4",
        "panel_4_description": "This panel will discuss the important role that space industry can play in addressing climate change. It will focus on how innovation stemming from the space sector can help create a more sustainable future. By looking at industry methods, future policies and development goals, the panel will identify issues and pinpoint opportunities for space technology and services to work together towards mitigating climate change by helping to enforce sustainability standards.",
        "industry_engagement": "Industry Engagement: How industry could engage in climate change mitigation based on sustainability criteria and a vision of future",
        "industries_pitches": "Industry Engagement: Brazilian Space Industries and Institutions' Pitches",
        "5minute": "5 minutes each",
        "closing": "Closing Ceremony",
        "troika": "Troika (Brazil, India and South Africa)",
        "iguazu_park": "Departure to Iguazu National Park (Iguazu Falls)",
        "return_recanto": "Return to Recanto Cataratas Thermas Resort & Convention"
    },    
    pt: {
        "day1": "Aquecimento",
        "day2": "Dia 1",
        "day3": "Dia 2",
        "day4": "Dia 3",
        "download": "Baixar PDF",
        "day1_schedule": "Aquecimento - 10 de setembro - Terça-feira",
        "time_1200": "12:00",
        "time_1700": "17:00",
        "time_1800": "18:00",
        "early_reg": "Registro Antecipado",
        "departure1": "1ª Saída para a Usina Hidrelétrica de Itaipu",
        "departure2": "2ª Saída para a Usina Hidrelétrica de Itaipu",
        "panoramic": "Vista Panorâmica",
        "panoramic_text": "Recepção de Boas-vindas na Usina Hidrelétrica Iluminada de Itaipu e Apresentação Cultural",
        "reception": "Recepção de Boas-vindas na Usina Hidrelétrica Iluminada de Itaipu",
        "time_2000": "20:00",
        "time_2100": "21:00",
        "return1": "1º Retorno ao Recanto Cataratas Thermas Resort & Convention",
        "return2": "2º Retorno ao Recanto Cataratas Thermas Resort & Convention",
        "day2_schedule": "Dia 1 - 11 de setembro - Quarta-feira",
        "day3_schedule": "Dia 2 - 12 de setembro - Quinta-feira",
        "day4_schedule": "Dia 3 - 13 de setembro - Sexta-feira",
        "registration": "Registro",
        "opening_Session": "Sessão de Abertura",
        "opening": "Sessão de Abertura pelos Anfitriões",
        "coffee": "Intervalo para Café e Abertura da Exposição",
        "heads_of_space_agencies_session": "Sessão dos Chefes das Agências Espaciais",
        "speech": "Discurso das Autoridades Brasileiras",
        "introduction": "Introdução ao tema da edição atual - Head, AEB",
        "experience_sharing": "Compartilhamento de Experiências da Edição Anterior do SELM G20 - Head, ISRO",
        "head_SANSA": "Mensagem do Próximo Anfitrião do SELM G20 - Head, SANSA",
        "message_host": "Declarações sobre o tema (3 minutos cada, Chefes das Agências + países convidados) Mensagem do Próximo Anfitrião do SELM - Head, SANSA",
        "photo": "Foto em Grupo",
        "lunch": "Intervalo para Almoço",
        "lunch_break": "Intervalo para Almoço e Visita à Exposição",
        "exhibition_opening": "Abertura da Exposição",
        "3_minute": "Declarações de 3 minutos cada, Chefes das Agências",
        "coffee_Snacks": "Intervalo para Café e Lanches servidos durante a Sessão",
        "declaration_introduction": "Introdução da Declaração",
        "presentation": "Apresentação da Declaração - Chefe, AEB",
        "impressions": "Impressões sobre a Declaração - Lista de Palestrantes, Apenas Membros do G20",
        "invited": "Declarações das Agências Espaciais Convidadas e Convidados sobre o tema",
        "panel_1": "Painel 1",
        "panel_1_description": "Este painel explorará a relação complexa entre a questão das mudanças climáticas e os objetivos do desenvolvimento sustentável. A discussão se concentrará nos desafios e nas oportunidades que surgem quando se busca integrar as mudanças climáticas e o desenvolvimento sustentável de forma eficaz. ",
        "climate_change_and_sustainable_development": "Mudança Climática e Desenvolvimento Sustentável",
        "panelists": "Palestrantes: Convidados e Chefes do G20, 10 minutos cada",
        "Moderator": "Moderadora: Sra. Leila Fonseca (Coordenadora de Estudos Estratégicos e Novos Negócios da AEB)",
        "challenges": "Desafios e oportunidades de integrar mudança climática e desenvolvimento sustentável",
        "coffee2": "Intervalo para Café e Visita à Exposição",
        "keynote_speech": "Palestra Principal: Thelma Krug (OMM)",
        "space_climate": "Espaço e Mudanças Climáticas: Desafios e Oportunidades",
        "adjourn": "Encerramento",
        "gala": "Jantar de Gala",
        "cultural": "Recepção (Usina Hidrelétrica de Itaipu Iluminada) e Apresentação Cultural",
        "panel_2": "Painel 2",
        "panel_2_description": "Este painel explorará a interface existente entre a economia espacial e o esforço de mitigação dos efeitos das mudanças climáticas, enfatizando a necessidade de estratégias coordenadas envolvendo governos, organizações internacionais, entidades do setor privado e comunidades locais. ",
        "Space_Economy_and_Climate_Change_Mitigation": "Economia Espacial e Mitigação da Mudança Climática: estratégias para ação coordenada",
        "panelists_hoa": "Palestrantes: Convidados e Chefes das Agências, 10 minutos cada",
        "Moderator_Chamon": "Moderador: Sr. Marco Antonio Chamon (Presidente da AEB)",
        "Moderator_AEB": "Moderador: AEB",
        "space_economy": "Economia Espacial e Mitigação da Mudança Climática: estratégias para ação coordenada",
        "hoa": "Iniciativas espaciais na mitigação da mudança climática",
        "remarks": "Comentários Finais",
        "ceremony": "Cerimônia de Assinatura da Declaração",
        "dinner": "Jantar Festivo",
        "panel_3": "Painel 3",
        "panel_3_description": "O painel discutirá como tecnologias espaciais podem ajudar a lidar com a questão das mudanças climáticas. Reunindo líderes e especialistas de agências espaciais, o painel explorará as perspectivas e recursos únicos que o espaço oferece para enfrentar esse desafio global complexo.  ",
        "space_initiatives": "Iniciativas Espaciais na Mitigação da Mudança Climática",
        "declaration_discussion_and_signature": "Discussão e Assinatura da Declaração",
        "0800_0900": "08:00 - 09:00",
        "0900_0945": "09:00 - 09:45",
        "0900_1030": "09:00 - 10:30",
        "0945_1015": "09:45 - 10:15",
        "1145_1315": "11:45 - 13:15",
        "1030_1100": "10:30 - 11:00",
        "1100_1230": "11:00 - 12:30",
        "1230_1300": "12:30 - 13:00",
        "1200_1400": "12:30 PM - 2:00 PM",
        "1015_1045": "10:15 - 10:45",
        "1300_1400": "13:00 - 14:00",
        "1300_1430": "13:00 - 14:30",
        "1315_1430": "13:15 - 14:30",
        "1400_1500": "14:00 - 15:00",
        "1430_1500": "14:30 - 15:00",
        "1430_1530": "14:30 - 15:30",
        "1430": "14:30",
        "1500_1530": "15:00 - 15:30",
        "1530_1600": "15:30 - 16:00",
        "1500_1700": "15:00 - 17:00",
        "1530_1700": "15:30 - 17:00",
        "1600_1800": "16:00 - 18:00",
        "1600_1700": "16:00 - 17:00",
        "1700_1800": "17:00 - 18:00",
        "1700_1730": "17:00 - 17:30",
        "1700": "17:00",
        "1730_1830": "17:30 - 18:30",
        "1800_1900": "18:00 - 19:00",
        "1830_1930": "18:30 - 19:30",
        "1900": "19:00",
        "1930_2200": "19:30 - 22:00",
        "1900_2200": "19:00 - 22:00",
        "2200": "22:00",
        "2300": "23:00",
        "1045_1145": "10:45 – 11:45",
        "g20_statements": "Declarações do G20 sobre o tema",
        "3_minute_statements": "(Declarações de 3 minutos cada, Chefes das Agências)",
        "coffee_snacks": "(Café e Lanches servidos durante a Sessão)",
        "90seconds": "Declarações de 90 segundos cada",
        "declaration": "Adoção da Declaração",
        "keynote_speech_unoosa": "Palestra Principal: Aarti Holla-Maini (UNOOSA)",
        "special_session_isro": "Sessão especial: Missão de Satélite G20 da ISRO",
        "speaker_isro": "Palestrante: ISRO",
        "session_chair_isro": "Presidente da Sessão: Sra. Márcia Alvarenga (Chefe da Assessoria de Cooperação Internacional da AEB)",
        "departure_to_festive_reception": "Saída para a Recepção Festiva",
        "festive_reception": "Recepção Festiva",
        "first_return": "1º Retorno ao Recanto Cataratas Thermas Resort & Convention",
        "second_return": "2º Retorno ao Recanto Cataratas Thermas Resort & Convention",
        "space_driver": "O Espaço como Motor para a Ação Climática",
        "panel_4": "Painel 4",
        "5minute": "5 minutos cada",
        "closing": "Cerimônia de Encerramento",
        "troika": "Troika (Brasil, Índia e África do Sul)",
        "iguazu_park": "Saída para o Parque Nacional do Iguaçu (Cataratas do Iguaçu)",
        "return_recanto": "Retorno ao Recanto Cataratas Thermas Resort & Convention",
        "panel_4_description": "Este painel discutirá o importante papel que a indústria espacial pode desempenhar no combate ao efeito das mudanças climáticas. A discussão se concentrará em como a inovação originada do setor espacial pode ajudar a criar um futuro mais sustentável. Ao analisar métodos da indústria, políticas futuras e metas de desenvolvimento, o painel identificará questões e apontará oportunidades para que a tecnologia e os serviços espaciais trabalhem juntos na mitigação das mudanças climáticas, ajudando a reforçar os padrões de sustentabilidade.",
        "industry_engagement": "Envolvimento da Indústria: como a indústria pode se envolver na mitigação da mudança climática com base em critérios de sustentabilidade e visão de futuro",
        "Moderator_Panel_3" : "Moderador: Sr. Rodrigo Leonardi (Diretor de Gestão de Portfólio da AEB)", 
        "Moderator_Panel_4" : "Moderador: Sr. Paolo Gessini (Diretor de Inteligência Estratégica e Novos Negócios da AEB)",

        "industries_pitches": "Envolvimento da Indústria: Apresentações das Indústrias e Instituições Espaciais Brasileiras",
    }
    
}